server-title: '&6&lHub'
servers:
  - Leagues
scoreboard:
  title: '&6&lHub'
  text:
    - '&7&m----------------'
    - '&eOnline Players'
    - ' %online% / 1000'
    - ' '
    - '&eRank:'
    - ' %rank%'
    - ' '
    - '&esomeserver.com'
    - '&7&m----------------'
  queuetext:
    - '&7&m----------------'
    - '&eOnline Players'
    - ' %online%/ 1000'
    - ' '
    - '&eRank:'
    - ' %rank%'
    - ' '
    - '&e&lQueue'
    - '%queuename% &7(#%queueposition%/%playersinqueue%'
    - '&e&msomeserver.com'
    - '&7&m----------------'
spawn:
  x: 0
  y: 70
  z: 0
ranks:
  default: '&e'
  Owner: '&4'
  Developer: '&b'
Leagues:
  lore:
    - '&7&m-----------------------------'
    - '&e  * &rStatus: %status%'
    - '&e  *  &rPlayers: %leaguesplayers%'
    - '&e  *  &rFaction Size &7: 10'
    - '&e  *  &rAllies&7: 1 Ally'
    - '&e  *  &fMap Kit&7: Prot 1 Sharp 1'
    - '&e  *  &fSOTW Timer&7: 1 Hour'
    - '&7&m-----------------------------'
tab:
  left-1: ''
  left-2: ''
  left-3: ''
  left-4: '&e&lServer'
  left-5: hub1
  left-6: ''
  left-7: ''
  left-8: ''
  left-9: ''
  left-10: ''
  left-11: '&e&lLeagues'
  left-12: '%leaguesstatus%'
  left-13: '&7%leaguesplayers%/100'
  left-14: ''
  left-15: ''
  left-16: ''
  left-17: ''
  left-18: ''
  left-19: ''
  left-20: ''
  middle-1: ''
  middle-2: '&6&lHub'
  middle-3: '&7Online: %online%/1000'
  middle-4: ''
  middle-5: '&e&lRank'
  middle-6: '%rank%'
  middle-7: ''
  middle-8: ''
  middle-9: ''
  middle-10: ''
  middle-11: '&e&lServer Info'
  middle-12: ''
  middle-13: ''
  middle-14: ''
  middle-15: ''
  middle-16: ''
  middle-17: ''
  middle-18: ''
  middle-19: ''
  middle-20: ''
  right-1: ''
  right-2: ''
  right-3: ''
  right-4: ''
  right-5: ''
  right-6: ''
  right-7: ''
  right-8: ''
  right-9: ''
  right-10: ''
  right-11: ''
  right-12: ''
  right-13: ''
  right-14: ''
  right-15: ''
  right-16: ''
  right-17: ''
  right-18: ''
  right-19: ''
  right-20: ''
